### ISSUE TITLE
js、css文件启用缓存

### ISSUE THREAD

**Issue by AinzRimuru** [vertex-app/vertex#10]
**简述需求**
目前每一次打开vertex都需要加载一次css、js等资源，这导致如果网速比较慢打开网页会变得非常卡。
qb的web界面在第一次打开后，后续的打开只需要100KB左右的流量。但是vertex需要4.4MB甚至更多，在网络速较差或者做种占满带宽的情况下会导致加载需要等待一分钟以上而且有可能会加载失败。
希望能够修改页面的加载流程，实现缓存。

**你的思路（如果有）**
可以参考qb的web界面的加载方式，直接使用link和script标签。

**补充信息**
无

**Comment by vertex-app** [comment]
这个问题吧，vue 打包出来这么大的，如果想从我这里优化体积的话要花点时间，暂时不会去考虑这个问题。
另外 拿 qb 来举例其实不太好，qb 有多少网页元素，vt 有多少网页元素。
其次，浏览器自己会缓存 js css 文件，第一次加载完之后短时间内刷新页面是不需要重新下载的。
4M 就目前网络用户群体来说不算太大，如果自己加载慢的话，注意自己的网络情况。
