### ISSUE TITLE
feature: 请问能支持pttime吗?

### ISSUE THREAD

**Issue by wxnode** [vertex-app/vertex#11]
**简述需求**
请问可以支持https://www.pttime.org/这个站吗?最近还挺火的

**你的思路（如果有）**
站点支持就好

**补充信息**
没有,感谢大佬了

**Comment by pusox** [comment]
已适配

[#a6ab7fa](https://github.com/vertex-app/vertex/commit/a6ab7fafebdca16d2efc0df2a2e05fea4b7a0e8c)

**Comment by vertex-app** [comment]
已适配

[#a6ab7fa](https://github.com/vertex-app/vertex/commit/a6ab7fafebdca16d2efc0df2a2e05fea4b7a0e8c)
