### ISSUE TITLE
feature: 删种规则新增限制下载速度选项

### ISSUE THREAD

**Issue by singworld** [vertex-app/vertex#12]
**简述需求**
删种规则里的暂停种子，能不能只暂停下载，不暂停上传。或者给下载限速1kb

**你的思路（如果有）**
因为遇到黑车，还有不错的上传速度。我这会停下来下载，还可以回本
或者遇到种子错误（本地磁盘满了等原因），还有不错的上传速度。 这会我如果不选择删除，必须对其下载进行暂停或者限速，不然等种子恢复进行追车，会导致大量下载
没找到暂停下载的功能，可对下载速度极限限速达到暂停下载的目的

**Comment by vertex-app** [comment]
好的。近期添加

**Comment by vertex-app** [comment]
已添加
[0bb119f](https://github.com/vertex-app/vertex/commit/0bb119f69e59cb5f1b17e1b59651b703f78e83e7)
