### ISSUE TITLE
能否添加硬链时顺便刮削

### ISSUE THREAD

**Issue by chenlu964** [vertex-app/vertex#13]
**简述需求**
下载完成后，自动硬链改名，顺便调用tmdb刮削文件

**你的思路（如果有）**
听说nastool是可以这样的，希望我们也添加一下

**Comment by vertex-app** [comment]
vt 本身有追剧功能，多看下功能介绍
至于刮削，去用 nastools 就可以了，这个功能 vt 不会做。
