### ISSUE TITLE
rss刷流错误:TypeError: Cannot read property 'alias' of undefined

### ISSUE THREAD

**Issue by wodepig** [vertex-app/vertex#14]
**简述问题**
几个pt的rss都不能自动下载,都是提示一样的错误,rss历史里面没有数据,qb不推送,软件内的qb日志也不更新

**简述环境**
![image](https://user-images.githubusercontent.com/42103087/214466965-aba8be28-9f23-4385-a8c2-111d45b30ab2.png)

搬瓦工服务器,docker方式安装,外网访问正常,下载器是qb,hz创建的按小时付费的机器,能正常链接和使用,鲨鱼,2xfree,馒头的rss订阅(第二个地址,能正常使用
**截图**
![image](https://user-images.githubusercontent.com/42103087/214467678-5ebceeeb-9db6-4b93-bfee-218134b54b1c.png)
![image](https://user-images.githubusercontent.com/42103087/214467716-74fff8cb-ce28-41bd-b95c-b9c41f12d88d.png)
![image](https://user-images.githubusercontent.com/42103087/214467749-a80bdfcd-62dd-4965-bb29-4472d996173d.png)
![image](https://user-images.githubusercontent.com/42103087/214467902-24528259-171e-4335-bc0d-3571abde9d8a.png)

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by wodepig** [comment]
![image](https://user-images.githubusercontent.com/42103087/214468223-911fc97f-4b19-47b1-acf0-2c0509881140.png)
错误信息忘记上传了

**Comment by vertex-app** [comment]
r创建 rss 规则的时候选择了下载器，这个下载器后来被你删掉了

**Comment by wodepig** [comment]
已解决,就是创建后又被我删除了
