### ISSUE TITLE
feature: 希望订阅历史加入搜索功能

### ISSUE THREAD

**Issue by Bespertrijun** [vertex-app/vertex#17]
**简述需求**
追的剧杂了，看到自己喜欢的，需要洗版的时候，想快速方便的看看自己下的是什么资源

**Comment by vertex-app** [comment]
好的，会抽空添加

**Comment by vertex-app** [comment]
已更新 https://github.com/vertex-app/vertex/commit/e61c375eebc5fc860907421512d8a6e749115bb6
