### ISSUE TITLE
feature: 希望能新增新兴站点SharkPT

### ISSUE THREAD

**Issue by wxnode** [vertex-app/vertex#20]
**简述需求**
望能新增新兴站点SharkPT
https://sharkpt.net/
这个站点刚开不久,但是很活跃,而且也有自己的开发,界面和功能都一天一个样.

**你的思路（如果有）**
如果有可行的实现思路，可以填写在这里

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by xylplm** [comment]
给力！

**Comment by wxnode** [comment]
非常感谢.
