### ISSUE TITLE
torrents文件夹

### ISSUE THREAD

**Issue by NOwin111** [vertex-app/vertex#23]
这个文件夹是用来存放推送的种子的吗？
“推送种子文件
是否直接推送种子文件, 默认推送种子下载链接至下载器”
这个我试了勾选或者不勾选都会生成种子文件到torrents文件夹。
如何可以“推送种子下载链接至下载器”

**Comment by vertex-app** [comment]
不勾选 推送种子文件 就是直接推送下载链接了。

个别站点会先下载种子文件计算 hash

**Comment by NOwin111** [comment]
0 23 * * * rm -f /root/vertex/torrents/*
计划任务加一条这个，每天23点清空torrents文件夹
