### ISSUE TITLE
feature: 希望"删种规则"增加"是否删除文件"选项

### ISSUE THREAD

**Issue by lkw199711** [vertex-app/vertex#27]
**简述需求**
我本地起了一个vt,准备专门用来管理种子. 来弥补有些没有做种子管理应用的补充. (autobangumi)
目前vt的删种默认是将文件一起删除. 如果(autobangumi)碰巧卡住,还没有进行重命名, vt把文件删掉,那么这个种子就白下载了.

**你的思路（如果有）**
![image](https://github.com/vertex-app/vertex/assets/38646029/63ab8c35-58a1-4f0c-8de0-97528de71ff1)
删种规则的设置里可以加一个开关,是否删除文件. 默认开启, 关闭则仅仅删除种子.

**补充信息**

**Comment by vertex-app** [comment]
https://github.com/vertex-app/vertex/commit/7ada59859030daefac69375734a50a6538e71a22
