### ISSUE TITLE
希望添加站点北邮人byrbt

### ISSUE THREAD

**Issue by Alozxy** [vertex-app/vertex#3]
**简述需求**
添加对北邮人pt站的支持, 主要是免费种子筛选功能

**你的思路（如果有）**
如果有可行的实现思路，可以填写在这里

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by vertex-app** [comment]
已添加~
我没 byr，你可以测试下看看，不正常再反馈

**Comment by Alozxy** [comment]
好的，我测试几天，非常感谢
