### ISSUE TITLE
"RSS任务"选项卡中的"等待时间"选项的功能不明确

### ISSUE THREAD

**Issue by Alozxy** [vertex-app/vertex#4]
**简述需求**

该选项的说明是:
若在 rss 时种子是非免费状态, 将在种子发布后的一段时间内重复抓取免费状态, 建议等待时间略小于 Rss 周期

通过阅读源码, 我发现它的逻辑是, 如果种子第一次rss抓取的时候如果判断为不免费, 且第一次抓取的时间在种子发布的T秒内(T为该选项的值), 那么存到redis里, 然后当第二次rss抓取并判断的时候, 如果依然不免费, 那么直接拒绝

我觉得更直观一点的逻辑应该是: 第一次rss后的T秒内, 每一次都重复判断是否免费, 超过T秒后才判断为不免费

**你的思路（如果有）**

源码的位置是: [这里](https://github.com/vertex-app/vertex/blob/e2aa94236fd221c8b401070252a6109ddc40c52c/app/common/Rss.js#L273)

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by vertex-app** [comment]
我这边的设定是：对于单个种子，最多抓取两次免费状态以减少对站点的影响。
如果按照你的思路，可能造成滥用。

**Comment by Alozxy** [comment]
原来如此, 非常感谢回答
