### ISSUE TITLE
bug: 首页中对部分站点的tracker统计有点问题

### ISSUE THREAD

**Issue by Lucien-Lin** [vertex-app/vertex#41]
**简述问题**
简述一下问题如何出现，提供正在使用的 Vertex 版本信息，版本信息可以在系统信息内查看。
突然发生的 
主版本0.0.14.0 | 编译版本7288c15cee42 | 发布时间2023-08-15 14:09:17 | 更新信息feat: zhuque & somebugfix
**简述环境**
简述一下 vertex 的安装环境，比如设备是什么 / 网络情况 / vertex 是否走了代理 / 代理所使用的云服务商等信息。
docker ds 918+  dsm7.1 
**截图**
最好能够提供一些截图，特别是日志，选择与发生错误时间相近的日志。
![1705020407588](https://github.com/vertex-app/vertex/assets/63552321/eb4f4a18-29df-4f7f-9f6c-ef625c0169ac)
ob连续上涨偶尔跌回正常,大概是一个到两个统计节点,一天能涨20MiB/s,现在是170+MiB/s 昨天是150+MiB/s
**补充信息**
如果你想提供其他信息，可以填在这里
无

**Comment by vertex-app** [comment]
两个客户端同时做种了同一个种子

**Comment by Lucien-Lin** [comment]
我排查了一下，没有发现。有办法查出来是哪个嘛
