### ISSUE TITLE
feature: 半夜停止删种

### ISSUE THREAD

**Issue by laobanguale** [vertex-app/vertex#44]
**简述需求**
在半夜（比如半夜12点到早上8点之间），pt站一般不会发新种子，所以这个时候如果删种的话，qb就会闲置下来造成资源浪费。如果在这个时间段停止删种，可以增加一些上传量。

**你的思路（如果有）**
目前我是在每条删种规则中都添加一个时间段的规则，但感觉有一些麻烦，毕竟要改一下时间得全部都改。如果能有一个开关实现半夜一个时间段内禁用全部删种规则就能优雅地实现这个功能了。

**Comment by vertex-app** [comment]
删种周期

**Comment by laobanguale** [comment]
存在一个问题，cron 表达式不能直接表示非连续的时间范围，比如我想在每天的 08:00-次日02:00  每分钟执行删种，这个情况就无法用一个cron 表达式实现了。

**Comment by vertex-app** [comment]
> 存在一个问题，cron 表达式不能直接表示非连续的时间范围，比如我想在每天的 08:00-次日02:00 每分钟执行删种，这个情况就无法用一个cron 表达式实现了。

`* 8-23,0-1 * * *`
