### ISSUE TITLE
mikan追番

### ISSUE THREAD

**Issue by chenlu964** [vertex-app/vertex#5]
**简述需求**
目前mikan追番如果订阅多个字幕组会多个字幕组的视频都下载一遍，很不方便

**你的思路（如果有）**
能不能类似追电视剧一样，比如第一集下载了A字幕组，那么B和C字幕组更新了第一集就跳过，以此类推后面更新了集数，只下载最先更新的字幕组，不重复下载

**Comment by vertex-app** [comment]
可以用规则限制字幕组？

vt 也可以考虑把蜜柑按照 PT 站的逻辑加入追剧任务，应该能满足你的需求

**Comment by chenlu964** [comment]
额 我目前是一个番订阅一个字幕组，如果能照 PT 站的逻辑推出追番任务是最好的了

**Comment by vertex-app** [comment]
已增加，使用中有问题再提
a134a7698f6e832740a44009ff174888c1b5db62
