### ISSUE TITLE
feature: 增加自动拆包功能

### ISSUE THREAD

**Issue by wzcsimon123** [vertex-app/vertex#51]
**简述需求**
只下载种子文件的一部分，自定义大小区间，如设置下载种子文件总大小 5%-10% 的文件，如果没有符合的文件（比如只有一个种子文件），就取消下载

**你的思路（如果有）**
添加下载时暂停 ，获取文件列表，从大到小排序，选出部分文件使其大小为种子文件总大小的 min% - max%，将其他文件的优先级设为0，然后开始下载。
如果没有符合的文件（比如只有一个种子文件），就取消下载。

**Comment by vertex-app** [comment]
不做拆包
