### ISSUE TITLE
bug:馒头子域名禁用导致的访问问题

### ISSUE THREAD

**Issue by dukewang2002** [vertex-app/vertex#55]
**简述问题**
馒头域名xp.m-team.io禁止访问，导致站点无法使用

**截图**
<img width="455" alt="1715937044047" src="https://github.com/vertex-app/vertex/assets/44317616/04d68e25-e55c-441c-bc68-9b07d546fd39">
<img width="470" alt="1715937140072" src="https://github.com/vertex-app/vertex/assets/44317616/390425ec-c307-4558-a404-7759e49fefc0">

**Comment by vertex-app** [comment]
更新版本可以解决
