### ISSUE TITLE
bug: 馒头下载种子失败

### ISSUE THREAD

**Issue by dukewang2002** [vertex-app/vertex#56]
**简述问题**
版本信息如下
主版本0.0.14.0 | 编译版本bc36d0106c00 | 发布时间2024-05-17 11:34:12
豆瓣订阅馒头下载种子失败，失败信息如下截图

**简述环境**
unraid下DOCKER安装 / 联通宽带 / vertex 未走代理 。

**截图**
![image](https://github.com/vertex-app/vertex/assets/44317616/050e1226-175e-4dae-8563-929fa807c9c7)

**Comment by vertex-app** [comment]
https://github.com/vertex-app/vertex/commit/e6d82ca7dd894ec2a86e41ae4235efbd06346192
