### ISSUE TITLE
feature: 自动开启或关闭站点rss任务

### ISSUE THREAD

**Issue by Pollo3470** [vertex-app/vertex#6]
**简述需求**
根据设定的分享率或上传量目标，自动启动或停止站点rss任务，智能管理流量和分享率

**你的思路（如果有）**
根据配置的站点，读取站点对应的上传量和分享率，判断是否达到设定的目标，达到则关闭rss任务，未达到则开启

**Comment by vertex-app** [comment]
目前不考虑在 vt 实现这个功能
