### ISSUE TITLE
bug: lusthive rss不能获取文件实际大小, 而是获取了种子大小

### ISSUE THREAD

**Issue by o0oo0ooo0** [vertex-app/vertex#68]
**简述问题**
lusthive rss不能获取文件实际大小, 而是获取了种子大小
rss任务时出现, 主版本0.0.14.0
**简述环境**
家宽, 没使用代理
**截图**
![firefox_fK8OqtZKrn](https://github.com/user-attachments/assets/1253fac1-d45f-4083-947f-510347a3abb7)

**补充信息**
这是rss的文件内容的一小段, 可以看出里面是包含所下载文件大小的

`All Torrents :: l****e https://l****e.org/ RSS feed for all new Torrent uploads. en-us Fri, 27 Sep 2024 14:01:46 +0000 http://blogs.law.harvard.edu/tech/rss Gazelle Feed Class [O****s.com] Bronze Goddess & Damion Dayski [1080p] https://l****e.org/torrents.php?id=1158 Interracial Fri, 27 Sep 2024 13:56:24 +0000 https://cdn.l****e.link/6a04eba66ab18f77b8977e0f398e0510.th.jpg https://cdn.l****e.link/c8070d1a5a9ecf9fc365e2ebfa3c89bc.th.jpg https://cdn.l****e.link/898421e8f01820a74b3db3493720b0b7.th.jpg https://cdn.l****e.link/f25b0429604ff044a94a8bd228be17d9.th.jpg https://cdn.l****e.link/82f249fc06b679f6b8d6c5e7ba9f67a3.th.jpg<br /><br />Starring : Bronze Goddess &amp; Damion Dayski<br />Subsite and site : O****s.com<br /><br />Production date : 2024<br />Genre : Interracial, IR, BBC, Straight, Homemade<br />Duration : 00:30:34<br /><br />Video type : 1080p<br />Video quality : SiteRip<br />Video format : MP4<br />Video : AVC, 1920x1080, 8,500 kb/s, 29.970 fps<br />Audio : AAC, 96.0 kb/s, 48.0 kHz, 2 channels<br /><br />https://cdn.l****e.link/f203f5fd5a9d6790c021ff8da2bbaf71.jpg interracial bbc straight homemade O****s.com bronze.goddess damion.dayski 1080p anon https://l****e.org/torrents.php?id=1158 https://l****e.org/torrents.php?id=1158 [p****b.net].t3118335.torrent %B1%CA%A9%D8%85s%CA%A4D%F4%3C6%12%BD%F9%97%ACO%1E%9E 1974321362 1.84 GiB [O****s.com] Bronze Goddess & Zac Wild [720p] https://l****e.org/torrents.php?id=1157 Homemade Fri, 27 Sep 2024 13:54:11 +0000 https://cdn.l****e.link/a9826efd33678877025ff5ef81865894.th.jpg https://cdn.l****e.link/b6c5ac1cd831a4cf7359f5ded71473bc.th.jpg https://cdn.l****e.link/155b0cf2e689c18d8dba77ef97858b7b.th.jpg https://cdn.l****e.link/2f6f88156fa439c87002b3ecde78d3c8.th.jpg https://cdn.l****e.link/ce39ba1a2aae60258c08b1a31555fcaa.th.jpg<br /><br />Starring : Bronze Goddess &amp; Zac Wild<br />Subsite &amp; Site : O****s.com<br /><br />Production date : 2024-09-21<br />Genre : Straight, Hardcore, Big Tits, Homemade<br />Duration : 00:39:00<br /><br />Video type : 720p<br />Video quality : SiteRip<br />Video format : MP4<br />Video : AVC, 1280x720, 8,492 kb/s, 29.970 fps<br />Audio : AAC, 96.0 kb/s, 48.0 kHz, 2 channels<br /><br />https://cdn.l****e.link/04bc100c98ac0cae79be0d22815fe079.jpg straight hardcore big tits homemade O****s.com bronze.goddess zac.wild 720p anon https://l****e.org/torrents.php?id=1157 https://l****e.org/torrents.php?id=1157 [p****b.net].t3118342.torrent %95%05V%E9%E3%80%CD%DDc%5B%AE%83%C9%60%8B%E8%CC%E8%B9%D7 2515008351 2.34 GiB
`

**Comment by vertex-app** [comment]
目前没适配这个站

**Comment by o0oo0ooo0** [comment]
#69
