### ISSUE TITLE
能否添加https反代-此贴终结 别回复了

### ISSUE THREAD

**Issue by chenlu964** [vertex-app/vertex#7]
**简述需求**
搭建在服务器上，不能https访问很烦，能不能内置https反代呢

**你的思路（如果有）**
类似emby一样，本地路径添加证书，然后指定端口访问https

**Comment by DOZZ9911** [comment]
同样的需求

**Comment by pusox** [comment]
已添加
使用方法参考：
[https://wiki.vertex.icu/zh/install/installation#%E5%85%B3%E4%BA%8E%E5%90%AF%E7%94%A8-https](url)

**Comment by vertex-app** [comment]
已添加
使用方法参考：
[https://wiki.vertex.icu/zh/install/installation#%E5%85%B3%E4%BA%8E%E5%90%AF%E7%94%A8-https](url)

**Comment by littlewu2508** [comment]
Enable https 和反代不是一个概念吧，希望的场景是由 apache2/nginx 等反代服务管理证书并统一 listen 443，然后 vertex 的 3000 端口只用 http 协议 listen to localhost

因为服务器上还会有其他 service，不可能所有 service 都监听 443，所以需要反代服务统一管理

**Comment by vertex-app** [comment]
> Enable https 和反代不是一个概念吧，希望的场景是由 apache2/nginx 等反代服务管理证书并统一 listen 443，然后 vertex 的 3000 端口只用 http 协议 listen to localhost
> 
> 因为服务器上还会有其他 service，不可能所有 service 都监听 443，所以需要反代服务统一管理

那自己装 nginx 等反代就好了啊。。。跟 vt 有什么关系
