### ISSUE TITLE
question: 想进群看视频结果莫名其妙被ban了？

### ISSUE THREAD

**Issue by moriecho** [vertex-app/vertex#72]
wiki的教程视频加载缓慢，于是加群，但是加群不到10秒就被ban了，一个视频都没看完

![image](https://github.com/user-attachments/assets/df8e40d6-8cff-42ea-884c-f297d1baa815)

tg名及头像：
![image](https://github.com/user-attachments/assets/e366ac0f-f0fe-4955-99c6-1ab9a7da8fae)

拼尽全力找不到其他的联系方式，只能在这留下issue希望作者看到给我解禁

**Comment by vertex-app** [comment]
已解，进群有人机验证，未验证会被封禁。

**Comment by moriecho** [comment]
> 已解，进群有人机验证，未验证会被封禁。

感谢，进群急着看视频去了，忘了过验证
