### ISSUE TITLE
feature: 建议增加一键清空RSS任务历史记录

### ISSUE THREAD

**Issue by reidmex** [vertex-app/vertex#73]
**简述需求**
增加一键清空RSS任务历史记录。RSS记录每天至少几百条甚至几千条，日积月累非常多，目前只能手工逐个删除，不支持批量删除

**你的思路（如果有）**
希望提供批量删除功能，如：
1）一键清空所有RSS记录
2）页面记录全选框，一次可以删除当前页所有RSS记录

**补充信息**
无

**Comment by reidmex** [comment]
这个项目还在维护吗？

**Comment by vertex-app** [comment]
https://github.com/vertex-app/vertex/commit/70cd0e2fe93d1df7ff71d72c09896e7099f2a505
