### ISSUE TITLE
bug: 服务器密钥登陆失败

### ISSUE THREAD

**Issue by yegetables** [vertex-app/vertex#74]
**简述问题**
简述一下问题如何出现，提供正在使用的 Vertex 版本信息，版本信息可以在系统信息内查看。
版本如图
服务器设置仅密钥登陆时会报错
密码登陆不会,但不安全
**简述环境**
简述一下 vertex 的安装环境，比如设备是什么 / 网络情况 / vertex 是否走了代理 / 代理所使用的云服务商等信息。
网络什么都很正常,新装的
**截图**
最好能够提供一些截图，特别是日志，选择与发生错误时间相近的日志。
![Clip_2024-10-26_17-20-26](https://github.com/user-attachments/assets/399323b6-34fc-4300-b311-58caba0a01cb)
![Clip_2024-10-26_17-21-55](https://github.com/user-attachments/assets/ea465559-5407-4b21-a7a3-6a18354b99fa)

![image](https://github.com/user-attachments/assets/282243b3-e84e-4ffb-abfc-9b6331141f3d)

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by vertex-app** [comment]
说明下具体的密钥加密方式以及其它信息

**Comment by yegetables** [comment]
应该是ED25519 RSA SHA256 什么的,需要的话我把详细日志发你tg,我看不太明白
