### ISSUE TITLE
bug: hdarea rss 一直"拒绝原因: 最长休眠时间"

### ISSUE THREAD

**Issue by o0oo0ooo0** [vertex-app/vertex#77]
**简述问题**
hdarea rss任务时出现, 其他pt网站的rss都没有问题
主版本: 0.0.14.0

**简述环境**
可以获取种子信息

**截图**
![r1vMcSYga2](https://github.com/user-attachments/assets/0fd705e7-8039-4c76-b360-83e85e00f0c4)

**补充信息**
如果你想提供其他信息，可以填在这里

**Comment by vertex-app** [comment]
https://wiki.vertex-app.top/chang-jian-wen-ti/chang-jian-wen-ti#ru-he-li-jie-zui-chang-xiu-mian-shi-jian

**Comment by o0oo0ooo0** [comment]
> https://wiki.vertex-app.top/chang-jian-wen-ti/chang-jian-wen-ti#ru-he-li-jie-zui-chang-xiu-mian-shi-jian

10 个 9可以关闭这个功能, 正常rss, 但只有hdarea在 * * * * *, 休眠时间180时一直无法正常加入种子, 这应该算bug吧
