### ISSUE TITLE
feature: 希望删除种子时能同时删除其他同名种子

### ISSUE THREAD

**Issue by DOZZ9911** [vertex-app/vertex#8]
**简述需求**
有时候会用来转种，这时候会有多个种子共享同一个文件，如果只删其中一个，其他的就变成做假种了

**你的思路（如果有）**
无，不过第三方qBittorrent WebUI有这个功能：[https://github.com/CzBiX/qb-web](https://github.com/CzBiX/qb-web)

**补充信息**
感谢栗大的开发，让配置RSS和删种规则变得如此轻松

**Comment by vertex-app** [comment]
同名+同大小+同路径文件，前几次删种不会删除文件，只会在确保无同种子的前提下才会删除文件。

**Comment by DOZZ9911** [comment]
这样啊，原来栗大早就考虑到这种情况了，那我可以放心删种了
