### ISSUE TITLE
bug: 对服务器限速后，Vertex识别实时上传/下载速度有误

### ISSUE THREAD

**Issue by DOZZ9911** [vertex-app/vertex#9]
**简述问题**
原本有网卡enp1s0，使用wondershaper对服务器限速，生成了一个虚拟网卡ifb0
使用sar -n命令检测当前网速，得到的结果如下：（ifb0的下载速度始终等于上传速度）
11:12:15 AM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
11:12:16 AM        lo     23.00     23.00      2.35      2.35      0.00      0.00      0.00      0.00
11:12:16 AM    enp1s0  16545.00   3010.00  22403.80   2268.11      0.00      0.00      0.00     18.35
11:12:16 AM      ifb0   4416.00   4416.00  16976.30  16976.30      0.00      0.00      0.00      0.00
11:12:16 AM   docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
此时，如果ifb0速度＞enp1s0速度，Vertex上显示的是ifb0的速度；如果ifb0速度＜enp1s0速度，Vertex上显示的是enp1s0的速度
如果用vnstat -l检测，则始终显示的是enp1s0的速度

**简述环境**
版本: 08042d4b69ea/2022-11-01 20:39:42

**截图**
sar -n检测：
![QQ截图20221114112602](https://user-images.githubusercontent.com/33958698/201569121-b0056a2d-07b0-457f-9860-152ae12f202e.png)
vnstat -l检测：
![QQ截图20221114112808](https://user-images.githubusercontent.com/33958698/201569202-3a24e8e4-c30c-498f-a843-597e89655e46.png)
ifb0速度＞enp1s0速度时，Vertex上的错误实时速度：
![QQ截图20221114112653](https://user-images.githubusercontent.com/33958698/201569335-b113c64d-5135-4d4c-920c-bb6b94f39341.png)
ifb0速度＜enp1s0速度时，Vertex上的正确实时速度：
![QQ截图20221114112708](https://user-images.githubusercontent.com/33958698/201569386-d7360697-0ba4-49a9-81ba-a4a4d9aaea55.png)

**补充信息**
下面用vnstat获取的的历史数据统计是正确的（如果可以的话，希望能把vnstat上的平均速率也加上），希望实时速度可以始终检测enp1s0，谢谢大佬

**Comment by vertex-app** [comment]
vt 显示的实时速度目前取的是所有网络设备中上传速度最大的一个，可以考虑在服务器内增加设置项指定网卡

**Comment by DOZZ9911** [comment]
解决了，在Server.js里面的var -n DEV加上--iface=enp1s0就行……

**Comment by DOZZ9911** [comment]
居然专门更新了一个版本，感谢栗大
